name: Run tests
on:
  push:
    branches:
      - "**" # matches every branch
jobs:
  run-rspec-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: 3.3.3
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Run sorbet typechecks
        run: |
          bundle exec srb tc --ignore examples
      - name: Run rspec tests
        run: |
          bundle exec rspec
